config/routes.rb
Rails.application.routes.draw do
  
  resources :product_sales
  resources :sites do
    member do
      put :site_product_sale
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :factory_collections, only:[:index, :show, :new, :create]
  
  resources :reports, only:[:index] do
    collection do
      post :generate_report
      get  :generate_report
    end
  end
  resources :history_clients
  resources :templates  do
    member {
      get :send_mail
      post :send_mail_confirm
      resources :email_histories
    }
  end

  resources :email_histories, only:[] do
    member {
      get :send_email
      post :send_mail_confirm
    }
  end
  
  resources :assignments do
    member do
      get :complete_assignment
      get :pdf_assignment
    end
    collection do
      get :factory_assignments
      post :factory_assignment_submit
    end
  end
  resources :routes  do
    member do
      get :manage_branches
      get :get_route_branches
    end
    collection do
      get :schedules
      post :add_collection
    end
  end
  resources :route_branches, only:[:show] do
    collection do
      post 'sort'
    end
  end
  resources :roles
  resources :cities do
    member do
      get :get_city_areas
    end
  end
  resources :states do
    resources :cities, only:[] do
      collection do
        get :get_state_cities
      end
    end
  end
  
  resources :products do
    collection do
      post 'sort'
    end
  end
 
 
  # get 'transactions/payment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  devise_for :users
  
  resources :dashboards
  resources :companies
  resources :storage_types
  resources :food_types
  resources :billings, only: [:index] do
    member do
      get :invoice
    end
  end
  resources :areas do
    collection do
      get :get_area_branches
    end
  end
  resources :vehicles do
    collection do
      get  'assignment'
      get 'assign_branches'
      get  'get_users'
      post 'assign_vehicle'
      post 'branches_assignment'
      delete 'unassigned_branch'
    end
  end
  resources :notes, only:[:index]
  resources :branches do
    member do
      post :update_branch_status
    end
    resources :notes
    resources :transactions, only: [:index] do
      collection do
        get 'payment'
        post 'create_payment'
      end
    end
  end
  resources :schedule_branches, only:[] do
    collection do
      get 'schedules'
    end
    
  end

  resources :collections
  resources :users, only: [:index, :new] do
    collection do
      post 'add_user'
    end
    member do
      delete 'block_unblock_user'
    end
  end
end

app/models/email_history.rb
class EmailHistory < ApplicationRecord
  has_many   :history_clients, dependent: :destroy
  belongs_to :template
end

# == Schema Information
#
# Table name: email_histories
#
#  id          :integer          not null, primary key
#  template_id :integer
#  html        :text
#  subject     :string
#  from_email  :string
#  cc          :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/email_histories_controller.rb
class EmailHistoriesController < ApplicationController
  # before_action :check_authorize_user
  
  def index
    @template        = Template.find_by_id(params[:id])
    @email_histories = @template.email_histories.order('created_at DESC')
  end
  
  def show
    respond_to do |format|
      @email_history   = EmailHistory.find_by_id(params[:id])
      @history_clients = @email_history.history_clients.count
      @branches        = Branch.count
      format.html
      format.js { render layout: false }
    end
  end
  
  def send_email
    @email_history       = EmailHistory.find_by_id(params[:id])
    @history_branch_ids  = @email_history.history_clients.pluck(:branch_id)
    @branches             = Branch.where.not(id: @history_branch_ids)
    @history_branches     = Branch.where(id: @history_branch_ids)
  end
  
  def send_mail_confirm
    # Send to new clients
    email_history  = EmailHistory.find_by_id(params[:id])
    params[:multiselect] && params[:multiselect].each do |branch_id|
      ClientMailer.delay.send_email_from_history(branch_id, email_history.id)
      client_history = email_history.history_clients.build
      client_history.branch_id = branch_id
      client_history.count     = 1
      client_history.save!
    end
    
    # Send again to clients
    params[:history_clients] && params[:history_clients].each do |branch_id|
      ClientMailer.delay.send_email_from_history(branch_id, email_history.id)
      client_history = email_history.history_clients.where(branch_id: branch_id).first
      client_history.count = client_history.count + 1
      client_history.save!
    end
    flash[:success] = 'Send mail in process.'
    redirect_to email_histories_path(email_history.template, email_history)
  end
end

app/helpers/email_histories_helper.rb
module EmailHistoriesHelper
end

app/views/email_histories/_show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @email_history.subject %>
    |
    <%= @email_history.from_email %>
    <div class="pull-right">
      <%= @history_clients %>
      /
      <%= @branches %>
    </div>
  </div>
  <div class="panel-body">
    <%= @email_history.html.html_safe %>
    <% #= text_area_tag('html', @email_history.html, size: '77x18', placeholder: 'Enter Html here', style: 'resize: none;', readonly: true) %>
  </div>
</div>
<div class="panel panel-warning">
  <div class="panel-heading">
    <%= 'Clients' %>
  </div>
  <div class="panel-body">
    <% h_clients  = @email_history.history_clients %>
    <table cellspacing="0" class="table table-striped table-bordered template-list-table" width="100%">
      <thead>
      <th>Email</th>
      <th>Email count</th>
      </thead>
      <tbody>
      <% h_clients && h_clients.each_with_index do |h_client,index| %>
          <tr>
            <td>
              <%= "#{h_client.branch.contact_email}" %>
            </td>
            <td>
              <%= "#{h_client.count}" %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/email_histories/index.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Email history</a></li>
  <li></li>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid simple ">
      <div class="grid-body no-border">
        <div class="row">
          <div class="col-md-5 vertical">
            <table cellspacing="0" class="table table-striped table-bordered list-data-table" width="100%">
              <thead>
              <th>Sr#</th>
              <th>Subject</th>
              <th>Actions</th>
              </thead>
              <tbody>
              <% @email_histories.each_with_index do |history,index| %>
                  <tr>
                    <td>
                      <%= index + 1 %>
                    </td>
                    <td>
                      <%= "#{history.subject}" %>
                    </td>
                    <td>
                      <%= link_to 'view', email_history_path(@template, history), remote: true %>
                      |
                      <%= link_to 'Send mail',  send_email_email_history_path(history) %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-md-7 vertical" id="show-parent">
            <div id="show"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/email_histories/send_email.html.erb
<style type="text/css">
  .ScrollRef .multiselect-container{
    max-height: 350px;
    overflow-y: auto;
  }
</style>

<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Send history email</a></li>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid simple ">
      <div class="grid-body no-border">
        <div class='row'>
  <div class="col-sm-8">
    <table class="table table-striped table-bordered">
      <tbody>
      <tr>
        <td><b>Subject:</b></td>
        <td>
          <%= @email_history.subject%>
          <span class='pull-right'><%= @history_branch_ids.count %> / <%= @branches.count + @history_branch_ids.count %></span>
        </td>
      </tr>
      <tr>
        <td><b>Sender:</b></td>
        <td><%= @email_history.from_email %></td>
      </tr>
      <tr>
        <td><b>Content:</b></td>
        <td>
          <%= @email_history.html.html_safe %>
          <%#= text_area_tag('html', @email_history.html, size: '80x18', placeholder: 'Enter Html here', style: 'resize: none;', readonly: true) %>
        </td>
      </tr>
      </tbody>
    </table>
    <%#= link_to 'click here', edit_template_path(@template), class: 'btn btn-primary btn-sm btn-round' %>
  </div>

  <div class="col-sm-4" style="height: 463px; position: relative;">
    <%= form_for(@email_history, url: send_mail_confirm_email_history_path(@email_history), method: 'post', :html => {:class => 'form-inline' }) do |f| %>
        <div class="form-group">
          <label> Already sent to: </label>
          <div  class="ScrollRef">
            <%= select_tag 'history_clients[]', options_for_select(@history_branches.collect {|p| [ p[:branch_name], p[:id] ] }), id: 'select_branches_for_email', class: 'form-control', style: 'width:30%;', multiple: 'multiple' %>
          </div>
        </div>
        <br/><br/>
        <div class="form-group">
          <label> Other Clients: </label>
          <div  class="ScrollRef">
            <%= select_tag 'multiselect[]', options_for_select(@branches.collect {|p| [ p[:branch_name], p[:id] ] }), id: 'send_clients', class: 'form-control', style: 'width:30%;', multiple: 'multiple' %>
          </div>
        </div>
        <div class="form-group" style="position:absolute; bottom: 0px; left: 15px;">
          <div>
            <%= f.submit 'Send Email', id: 'sent_email_button', :class => 'btn btn-primary btn-sm', data: { confirm: 'Are you sure to send email?' }, disabled: true %>
          </div>
        </div>
    <% end %>
    <div id='selected_clients' class="emailslistspan" style="width: 100%; margin: 10px 0 0 0; height: 344px; overflow-y: auto;"></div>
  </div>
</div>
      </div>
    </div>
  </div>
</div>

app/views/email_histories/show.js.erb
jQuery("#show").html('<%= escape_javascript(render :partial => "show") %>');
$("#show-parent").scrollTo("#show", 500);