config/routes.rb
Rails.application.routes.draw do
  
  resources :product_sales
  resources :sites do
    member do
      put :site_product_sale
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :factory_collections, only:[:index, :show, :new, :create]
  
  resources :reports, only:[:index] do
    collection do
      post :generate_report
      get  :generate_report
    end
  end
  resources :history_clients
  resources :templates  do
    member {
      get :send_mail
      post :send_mail_confirm
      resources :email_histories
    }
  end

  resources :email_histories, only:[] do
    member {
      get :send_email
      post :send_mail_confirm
    }
  end
  
  resources :assignments do
    member do
      get :complete_assignment
      get :pdf_assignment
    end
    collection do
      get :factory_assignments
      post :factory_assignment_submit
    end
  end
  resources :routes  do
    member do
      get :manage_branches
      get :get_route_branches
    end
    collection do
      get :schedules
      post :add_collection
    end
  end
  resources :route_branches, only:[:show] do
    collection do
      post 'sort'
    end
  end
  resources :roles
  resources :cities do
    member do
      get :get_city_areas
    end
  end
  resources :states do
    resources :cities, only:[] do
      collection do
        get :get_state_cities
      end
    end
  end
  
  resources :products do
    collection do
      post 'sort'
    end
  end
 
 
  # get 'transactions/payment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  devise_for :users
  
  resources :dashboards
  resources :companies
  resources :storage_types
  resources :food_types
  resources :billings, only: [:index] do
    member do
      get :invoice
    end
  end
  resources :areas do
    collection do
      get :get_area_branches
    end
  end
  resources :vehicles do
    collection do
      get  'assignment'
      get 'assign_branches'
      get  'get_users'
      post 'assign_vehicle'
      post 'branches_assignment'
      delete 'unassigned_branch'
    end
  end
  resources :notes, only:[:index]
  resources :branches do
    member do
      post :update_branch_status
    end
    resources :notes
    resources :transactions, only: [:index] do
      collection do
        get 'payment'
        post 'create_payment'
      end
    end
  end
  resources :schedule_branches, only:[] do
    collection do
      get 'schedules'
    end
    
  end

  resources :collections
  resources :users, only: [:index, :new] do
    collection do
      post 'add_user'
    end
    member do
      delete 'block_unblock_user'
    end
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  load_and_authorize_resource
  before_action :set_branch, only: [:show, :edit, :update, :destroy]
  
  def index
    if params[:type].present?
      @type = params[:type]
      if @current_user_role == AppConstants::PFA
        company_ids = Company.where(site_id: @current_user_site.id).pluck(:id)
        @branches   = Branch.where(branch_status: params[:type], company_id: company_ids).includes(:company)
      else
        @branches = @branches.where(branch_status: params[:type]).includes(:company)
      end
      
      if params[:type] == AppConstants::VISIT
        @statuses = [AppConstants::VISIT, AppConstants::LEAD, AppConstants::CONTRACTED]
      elsif params[:type] == AppConstants::LEAD
        @statuses = [AppConstants::LEAD, AppConstants::CONTRACTED]
      elsif params[:type] == AppConstants::CONTRACTED
        @statuses = [AppConstants::CONTRACTED]
      else
        @branches = Branch.where(branch_status: AppConstants::CONTRACTED).includes(:company)
        @statuses = [AppConstants::CONTRACTED]
      end
    else
      @branches = @branches.where(branch_status: AppConstants::CONTRACTED).includes(:company)
      @statuses = [AppConstants::CONTRACTED]
    end
  end
  
  def show
    authorize :branch
  end
  
  def new
    @branch = Branch.new
    if not @current_user_site.is_automate_process
      @statuses = [AppConstants::CONTRACTED]
    else
      @statuses = [AppConstants::VISIT, AppConstants::LEAD, AppConstants::CONTRACTED]
    end
    
    
    role                  = Role.find_by_name(AppConstants::SALER)
    @sale_representatives = User.where(site_id: @current_user_site.id, role_id: role.id, is_deleted: false)
    @companies            = Company.where(site_id: @current_user_site.id, is_deleted: false)
    @food_types           = FoodType.where(site_id: @current_user_site.id, is_deleted: false)
    @storage_types        = StorageType.where(site_id: @current_user_site.id, is_deleted: false)
    @states               = State.where(is_deleted: false)
    @cities               = City.where(is_deleted: false)
    @areas                = Area.where(site_id: @current_user_site.id)
  end
  
  def edit
    role                  = Role.find_by_name(AppConstants::SALER)
    @companies            = Company.where(site_id: @current_user_site.id, is_deleted: false)
    @sale_representatives = User.where(site_id: @current_user_site.id, role_id: role.id, is_deleted: false)
    @food_types           = FoodType.where(site_id: @current_user_site.id, is_deleted: false)
    @storage_types        = StorageType.where(site_id: @current_user_site.id, is_deleted: false)
    @states               = State.where(is_deleted: false)
    @cities               = City.where(is_deleted: false)
    @areas                = Area.where(site_id: @current_user_site.id)
    
    if @branch.branch_status == AppConstants::VISIT
      @statuses = [AppConstants::VISIT, AppConstants::LEAD, AppConstants::CONTRACTED]
    elsif @branch.branch_status == AppConstants::LEAD
      @statuses = [AppConstants::LEAD, AppConstants::CONTRACTED]
    elsif @branch.branch_status == AppConstants::CONTRACTED
      @statuses = [AppConstants::CONTRACTED]
    end
  end
  
  def create
    if params[:branch][:area_name].present?
      area          = Area.find_by_name_and_site_id(params[:branch][:area_name], @current_user_site.id) || Area.new(site_id: @current_user_site.id)
      area.state_id = params[:branch][:state_id]
      area.city_id  = params[:branch][:city_id]
      area.name     = params[:branch][:area_name]
      area.save if area.new_record?
    end
    
    if params[:branch][:company_name].present?
      company              = Company.find_by_company_name_and_site_id(params[:branch][:company_name], @current_user_site.id) || Company.new(site_id: @current_user_site.id)
      company.company_name = params[:branch][:company_name]
      company.save if company.new_record?
    end

    @branch            = Branch.new(branch_params)
    @branch.area_id    = area.id if area.present?
    @branch.company_id = company.id if company.present?
    
    respond_to do |format|
      if @branch.save
        @branch.update_status_and_code
        format.html { redirect_to branches_path({ type: AppConstants::CONTRACTED }), notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        if @current_user_site.is_automate_process
          @statuses = [AppConstants::CONTRACTED]
        else
          @statuses = [AppConstants::VISIT, AppConstants::LEAD, AppConstants::CONTRACTED]
        end
        role                  = Role.find_by_name(AppConstants::SALER)
        @sale_representatives = User.where(role_id: role.id)
        @companies            = Company.where(site_id: @current_user_site.id, is_deleted: false)
        @food_types           = FoodType.where(site_id: @current_user_site.id, is_deleted: false)
        @storage_types        = StorageType.where(site_id: @current_user_site.id, is_deleted: false)
        @states               = State.where(is_deleted: false)
        @cities               = City.where(is_deleted: false)
        @areas                = Area.where(site_id: @current_user_site.id)
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        @branch.update_status_and_code
        format.html { redirect_to branches_path({ type: AppConstants::CONTRACTED }), notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        role                  = Role.find_by_name(AppConstants::SALER)
        @companies            = Company.where(site_id: @current_user_site.id, is_deleted: false)
        @sale_representatives = User.where(site_id: @current_user_site.id, role_id: role.id, is_deleted: false)
        @food_types           = FoodType.where(site_id: @current_user_site.id, is_deleted: false)
        @storage_types        = StorageType.where(site_id: @current_user_site.id, is_deleted: false)
        @states               = State.where(is_deleted: false)
        @cities               = City.where(is_deleted: false)
        @areas                = Area.where(site_id: @current_user_site.id)
        
        if @branch.branch_status == AppConstants::VISIT
          @statuses = [AppConstants::VISIT, AppConstants::LEAD, AppConstants::CONTRACTED]
        elsif @branch.branch_status == AppConstants::LEAD
          @statuses = [AppConstants::LEAD, AppConstants::CONTRACTED]
        elsif @branch.branch_status == AppConstants::CONTRACTED
          @statuses = [AppConstants::CONTRACTED]
        end
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_branch_status
    @branch               = Branch.find_by_id(params[:id])
    @branch.branch_status = params[:status]
    @branch.save(validate: false)
    @branch.update_status_and_code
    return render json: true
  end
  
  def destroy
    authorize :branch
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  def set_branch
    @branch = Branch.find(params[:id])
  end
  
  def branch_params
    params.require(:branch).permit(:company_id, :branch_name, :contract_type, :branch_code, :area_id, :contact_name, :rate_per_kg, :contact_email, :contact_phone, :number_of_outlets, :food_type_id, :monthly_oil_used, :storage_type_id, :city_id, :street, :state_id, :zip, :latitude, :longitude, :branch_status, :representative, :visits_per_month, :area_name, :company_name)
  end
end

app/views/branches/_automate_form.html.erb
<%= simple_form_for(@branch) do |f| %>

    <% if @branch.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul>
            <% @branch.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-text_fields">
      <div class="panel panel-default">
        <div class="panel-heading">
          Branch Info
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3 form-group">
              <%= f.label 'Company' %>
              <%= f.select :company_id, options_for_select(@companies.collect { |p| [p[:company_name], p[:id]] }, selected: @branch.company_id), { include_blank: 'Select company' }, class: 'form-control ' %>
            </div>

            <div class="col-md-3 form-group">
              <%= f.text_field :company_name, placeholder: 'Other Company', style: 'margin-top: 11%;' %>
            </div>


            <div class="col-md-3">
              <%= f.label 'Branch name' %>
              <%= f.text_field :branch_name, class: 'form-control', placeholder: 'branch name' %>
            </div>
            <div class="col-md-3 form-group">
              <%= f.label 'Contract type' %>
              <%= f.select :contract_type, options_for_select(AppConstants::CONTRACT_STATUS), class: 'form-control' %>
            </div>

          </div>
          <div class="row">
            <div class="col-md-3 form-group">
              <%= f.label 'Status' %>
              <%= f.select :branch_status, options_for_select(@statuses), class: 'form-control' %>
            </div>
            <div class="col-md-3 form-group">
              <%= f.label 'Sale representative' %>
              <!--dropdown_easy_selection-->
              <%= f.select :representative, options_for_select(@sale_representatives.collect { |p| [p[:name] || p[:email], p[:id]] }, selected: @branch.try(:representative)), { include_blank: 'Select saler' }, class: 'form-control ' %>
            </div>
            <div class="col-md-3 form-group">
              <%= f.label '# of visits' %>
              <%= f.number_field :visits_per_month, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Contact Info
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3 form-group">
              <%= f.label 'Contact name' %>
              <%= f.text_field :contact_name, class: 'form-control', placeholder: 'cont. name' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Contact email' %>
              <%= f.text_field :contact_email, class: 'form-control', placeholder: 'cont. email' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Contact phone' %>
              <%= f.number_field :contact_phone, class: 'form-control', placeholder: 'cont. phone' %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3 form-group">
              <%= f.label 'Contact name' %>
              <%= f.text_field :contact_name1, class: 'form-control', placeholder: 'cont. name' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Contact email' %>
              <%= f.text_field :contact_email1, class: 'form-control', placeholder: 'cont. email' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Contact phone' %>
              <%= f.number_field :contact_phone1, class: 'form-control', placeholder: 'cont. phone' %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Misc Info
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3">
              <%= f.label 'Type of establishment' %>
              <!--dropdown_easy_selection-->
              <%= f.select :food_type_id, options_for_select(@food_types.collect { |p| [p[:name], p[:id]] }, selected: @branch.try(:food_type_id)), { include_blank: 'Select Food type' }, class: 'form-control ' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Monthly oil used (kg)' %>
              <%= f.text_field :monthly_oil_used, class: 'form-control', placeholder: 'oil used (kg)' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Rate/kg' %>
              <%= f.number_field :rate_per_kg, class: 'form-control', placeholder: 'amount/kg' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Storage type' %>
              <%= f.select :storage_type_id, options_for_select(@storage_types.collect { |p| [p[:name], p[:id]] }, selected: @branch.try(:storage_type_id)), class: 'form-control' %>
            </div>
          </div>

        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Address Info
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3">
              <%= f.select :state_id, options_for_select(@states.collect { |p| [p[:name], p[:id]] }, selected: @branch.state_id), { include_blank: 'Select sate' }, class: 'form-control' %>
            </div>
            <div class="col-md-3">
              <%= f.select :city_id, options_for_select(@cities.collect { |p| [p[:name], p[:id], {parent_id: p.state_id}]}, selected: @branch.city_id), { include_blank: 'Select city' }, class: 'form-control' %>
            </div>
            <div class="col-md-3">
              <%= f.select :area_id, options_for_select(@areas.collect { |p| [p[:name], p[:id], {parent_id: p.city_id}] }, selected: @branch.area_id), { include_blank: 'Select area' }, class: 'form-control' %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :area_name, placeholder: 'Other Area' %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3">
               <%= f.text_field :street, placeholder: 'street' %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :zip, placeholder: 'zip' %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Lat/Long
        </div>
        <div class="panel-body">
          <div class="col-md-3">
            <%= f.text_field :latitude, placeholder: 'latitude' %>
          </div>

          <div class="col-md-3">
            <%= f.text_field :longitude, placeholder: 'longitude' %>
          </div>
        </div>
      </div>
    </div>
    <div class="form-actions">
      <%= link_to 'Back', branches_path, class: 'btn btn-mini btn-default' %>
      <%= f.button :submit, class: 'btn btn-mini btn-primary' %>
    </div>
<% end %>

app/views/branches/_manual_form.html.erb
<%= simple_form_for(@branch) do |f| %>

    <% if @branch.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul>
            <% @branch.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-text_fields">
      <div class="panel panel-default">
        <div class="panel-heading">
          Branch Info
        </div>
        <div class="panel-body">
          <div class="row">
            <%#= f.hidden_field :company_id, value: @companies.first.id %>
            <%= f.hidden_field :branch_status, value: 'contracted' %>
            <%= f.hidden_field :visits_per_month, value: 5 %>
            <%= f.hidden_field :food_type_id, value: @food_types.first.id %>
            <%= f.hidden_field :storage_type_id, value: @storage_types.first.id %>
            <div class="col-md-3 form-group">
              <%= f.label 'Company' %>
              <%= f.select :company_id, options_for_select(@companies.collect { |p| [p[:company_name], p[:id]] }, selected: @branch.company_id), { include_blank: 'Select company' }, class: 'form-control ' %>
            </div>

            <div class="col-md-3 form-group">
              <%= f.text_field :company_name, placeholder: 'Other Company', style: 'margin-top: 11%;' %>
            </div>
            <div class="col-md-3">
              <%= f.label 'Branch name' %>
              <%= f.text_field :branch_name, class: 'form-control', placeholder: 'branch name' %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Contact Info
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3 form-group">
              <%= f.label 'Contact name' %>
              <%= f.text_field :contact_name, class: 'form-control', placeholder: 'cont. name' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Contact email' %>
              <%= f.text_field :contact_email, class: 'form-control', placeholder: 'cont. email' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Contact phone' %>
              <%= f.number_field :contact_phone, class: 'form-control', placeholder: 'cont. phone' %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Misc Info
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3">
              <%= f.label 'Monthly oil used (kg)' %>
              <%= f.text_field :monthly_oil_used, class: 'form-control', placeholder: 'oil used (kg)' %>
            </div>

            <div class="col-md-3">
              <%= f.label 'Rate/kg' %>
              <%= f.number_field :rate_per_kg, class: 'form-control', placeholder: 'amount/kg' %>
            </div>
          </div>

        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          Address Info
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3">
              <%= f.select :state_id, options_for_select(@states.collect { |p| [p[:name], p[:id]] }, selected: @branch.state_id), { include_blank: 'Select sate' }, class: 'form-control' %>
            </div>
            <div class="col-md-3">
              <%= f.select :city_id, options_for_select(@cities.collect { |p| [p[:name], p[:id], { parent_id: p.state_id }] }, selected: @branch.city_id), { include_blank: 'Select city' }, class: 'form-control' %>
            </div>
            <div class="col-md-3">
              <%= f.select :area_id, options_for_select(@areas.collect { |p| [p[:name], p[:id], { parent_id: p.city_id }] }, selected: @branch.area_id), { include_blank: 'Select area' }, class: 'form-control' %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :area_name, placeholder: 'Other Area' %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-3">
              <%= f.text_field :street, placeholder: 'street' %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :zip, placeholder: 'zip' %>
            </div>
          </div>

          <div class="col-md-3">
            <% if @branch.area_id.present? %>
                <%= f.text_field :zip, placeholder: 'zip' %>
            <% else %>
                <%= f.text_field :zip, placeholder: 'zip', class: 'hidden' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <%= link_to 'Back', branches_path, class: 'btn btn-mini btn-default' %>
      <%= f.button :submit, class: 'btn btn-mini btn-primary' %>
    </div>
<% end %>

app/views/branches/edit.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Edit Branch</a></li>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid-body no-border">
      <% if @current_user_site.is_automate_process %>
          <%= render 'automate_form', branch: @branch %>
      <% else %>
          <%= render 'automate_form', branch: @branch %>
      <% end %>
    </div>
  </div>
</div>

app/views/branches/index.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Branches</a></li>
  <%# if can? :new, Branch %>
  <% if @current_user_role == AppConstants::PFA  %>
      <% if not @current_user_site.is_automate_process %>
          <li><%= link_to 'New Branch', new_branch_path, class: 'btn btn-mini btn-primary' %></li>
      <% end %>
  <% else %>
          <li><%= link_to 'New Branch', new_branch_path, class: 'btn btn-mini btn-primary' %></li>
  <% end %>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid-body no-border">
      <table class="table table-striped" id="branches_index_table">
        <thead>
        <tr>
          <th>Company</th>
          <th>Area</th>
          <% if @type.present? && @type == AppConstants::CONTRACTED %>
              <th>Code (C/B)</th>
          <% end %>
          <th>Branch</th>
          <th>Sale Person</th>
          <th>Cont. phone</th>
          <% if @type.present? && @type == AppConstants::CONTRACTED %>
              <th>Rate/KG</th>
          <% end %>
          <th>Status</th>
          <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @branches.each do |branch| %>
            <tr id='<%= "#{branch.id}" %>'>
              <td><%= "#{branch.company.company_name}" %></td>
              <td style="width: 20%;"><%= branch.try(:area).try(:name) || 'N/A' %></td>
              <% if @type.present? && @type == AppConstants::CONTRACTED %>
                  <td><%= "#{branch.company.company_code}/#{branch.branch_code}" %></td>
              <% end %>
              <td><%= branch.branch_name %></td>
              <td><%= branch.representator.try(:name) || branch.representator.try(:email) %></td>
              <td><%= branch.contact_phone %></td>
              <% if @type.present? && @type == AppConstants::CONTRACTED %>
                  <td><%= branch.rate_per_kg %></td>
              <% end %>
              <td>
                <%= select_tag 'status', options_for_select(@statuses, selected: branch.branch_status), class: 'form-control branch_change_status' %>
              </td>
              <td style="width: 17%;">
                <%# if can? :show, branch %>
                    <%#= link_to 'show', branch, class: 'btn btn-mini btn-success' %>
                <%# end %>

                <%# if can? :update, branch %>
                    <%#= link_to 'edit', edit_branch_path(branch), class: 'btn btn-mini btn-primary' %>
                <%# end %>

                <%# if can? :index, Note %>
                    <%#= link_to 'notes', branch_notes_path(branch), class: 'btn btn-mini btn-warning' %>
                <%# end %>

                <% if @current_user_role == AppConstants::PFA %>
                    <% if not @current_user_site.is_automate_process %>
                      <%= link_to 'show', branch, class: 'btn btn-mini btn-success' %>
                      <%= link_to 'edit', edit_branch_path(branch), class: 'btn btn-mini btn-primary' %>
                      <%= link_to 'notes', branch_notes_path(branch), class: 'btn btn-mini btn-warning' %>
                    <% end %>
                <% else %>
                    <%= link_to 'show', branch, class: 'btn btn-mini btn-success' %>
                    <%= link_to 'edit', edit_branch_path(branch), class: 'btn btn-mini btn-primary' %>
                    <%= link_to 'notes', branch_notes_path(branch), class: 'btn btn-mini btn-warning' %>
                <% end %>






              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/branches/new.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">New Branch</a></li>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid-body no-border">
      <% if @current_user_site.is_automate_process %>
        <%= render 'automate_form', branch: @branch %>
      <% else %>
          <%= render 'manual_form', branch: @branch %>
      <% end %>
    </div>
  </div>
</div>

app/views/branches/show.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Branch details</a></li>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid-body no-border">

        <div class="row">
          <div class="col-md-4">
            <fieldset class="fieldset-border">
              <legend class="fieldset-border">Branch details</legend>
              <b>Company:</b>        <%= @branch.company.company_name %><br>
              <b>Area:</b>           <%= @branch.try(:area).try(:name) || 'N/A' %><br>
              <b>Branch name:</b>    <%= @branch.branch_name || 'N/A' %><br>
              <b>Sale Person:</b> <%= @branch.representator.try(:name) || @branch.representator.try(:email) %><br>
              <b>Status:</b>       <%= @branch.branch_status %><br>
              <% if @branch_status == 'contracted' %>
                  <b>Code (c/B):</b>  <%= "#{@branch.company.company_code}/#{@branch.branch_code}" %>
              <% end %>
            </fieldset>
          </div>
          <div class="col-md-4">
            <fieldset class="fieldset-border">
              <legend class="fieldset-border">Contact details</legend>
              <b>Contact name:</b>   <%= @branch.contact_name || 'N/A' %><br>
              <b>Contact email:</b>  <%= @branch.contact_email || 'N/A' %><br>
              <b>Contact#:</b>       <%= @branch.contact_phone || 'N/A' %><br>
            </fieldset>
          </div>
          <div class="col-md-4">
            <fieldset class="fieldset-border">
              <legend class="fieldset-border">Misc details</legend>
              <b>Type of food:</b>     <%= @branch.try(:food_type).try(:name) || 'N/A' %><br>
              <b>Storage type:</b>     <%= @branch.try(:storage_type).try(:name) || 'N/A' %><br>
              <b>Monthly oil used:</b> <%= @branch.monthly_oil_used || 'N/A' %><br>
              <b>Rate/KG:</b>     <%= @branch.rate_per_kg || 'N/A' %><br>
            </fieldset>
          </div>
        </div>

        <div class="">
          <fieldset class="fieldset-border">
            <legend class="fieldset-border">Misc details</legend>
            <b>Address:</b>     <%= @branch.address %><br>
          </fieldset>
        </div>


        <%= link_to 'Back', branches_path, class: 'btn btn-mini btn-default' %>
        <%= link_to 'Edit', edit_branch_path(@branch), class: 'btn btn-mini btn-primary' %>
      </div>
  </div>
</div>