config/routes.rb
Rails.application.routes.draw do
  
  resources :product_sales
  resources :sites do
    member do
      put :site_product_sale
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :factory_collections, only:[:index, :show, :new, :create]
  
  resources :reports, only:[:index] do
    collection do
      post :generate_report
      get  :generate_report
    end
  end
  resources :history_clients
  resources :templates  do
    member {
      get :send_mail
      post :send_mail_confirm
      resources :email_histories
    }
  end

  resources :email_histories, only:[] do
    member {
      get :send_email
      post :send_mail_confirm
    }
  end
  
  resources :assignments do
    member do
      get :complete_assignment
      get :pdf_assignment
    end
    collection do
      get :factory_assignments
      post :factory_assignment_submit
    end
  end
  resources :routes  do
    member do
      get :manage_branches
      get :get_route_branches
    end
    collection do
      get :schedules
      post :add_collection
    end
  end
  resources :route_branches, only:[:show] do
    collection do
      post 'sort'
    end
  end
  resources :roles
  resources :cities do
    member do
      get :get_city_areas
    end
  end
  resources :states do
    resources :cities, only:[] do
      collection do
        get :get_state_cities
      end
    end
  end
  
  resources :products do
    collection do
      post 'sort'
    end
  end
 
 
  # get 'transactions/payment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  devise_for :users
  
  resources :dashboards
  resources :companies
  resources :storage_types
  resources :food_types
  resources :billings, only: [:index] do
    member do
      get :invoice
    end
  end
  resources :areas do
    collection do
      get :get_area_branches
    end
  end
  resources :vehicles do
    collection do
      get  'assignment'
      get 'assign_branches'
      get  'get_users'
      post 'assign_vehicle'
      post 'branches_assignment'
      delete 'unassigned_branch'
    end
  end
  resources :notes, only:[:index]
  resources :branches do
    member do
      post :update_branch_status
    end
    resources :notes
    resources :transactions, only: [:index] do
      collection do
        get 'payment'
        post 'create_payment'
      end
    end
  end
  resources :schedule_branches, only:[] do
    collection do
      get 'schedules'
    end
    
  end

  resources :collections
  resources :users, only: [:index, :new] do
    collection do
      post 'add_user'
    end
    member do
      delete 'block_unblock_user'
    end
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :branch
end

# == Schema Information
#
# Table name: notes
#
#  id              :integer          not null, primary key
#  branch_id       :integer
#  comment         :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  completed_notes :text
#  is_completed    :boolean
#

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_branch, only: [:index, :new, :create, :edit, :update, :destroy]
  
  def index
    if params[:branch_id].present?
      @notes = @branch.notes.order('created_at DESC')
    else
      @notes = Note.all.group_by { |d| d[:branch_id] }
    end
  end
  
  def new
    @note = @branch.notes.build
  end

  def edit
    @note = Note.find_by_id(params[:id])
  end

  def create
    @note = @branch.notes.new(note_params)
    
    respond_to do |format|
      if @note.save
        format.html { redirect_to branch_notes_path(@branch), notice: 'Note was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @note = Note.find_by_id(params[:id])
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to branch_notes_path(@branch), notice: 'Note was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @note = Note.find_by_id(params[:id])
    @note.destroy
    respond_to do |format|
      format.html { redirect_to branch_notes_path(@branch), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_branch
      @branch = Branch.find_by_id(params[:branch_id])
    end

    def note_params
      params.require(:note).permit(:branch_id, :comment, :completed_notes, :site_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note, url: url, method: type) do |f| %>
    <% if @note.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@note.errors.count, "error") %> prohibited this task from being saved:</h2>
          <ul>
            <% @note.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="form-inputs">
    <%= f.label :comment%>
    <%= f.hidden_field :site_id,value:  @current_user_site.id %>
    <%= f.text_area :comment, size: "50x10", placeholder: 'Enter comment here...' %>
  </div>
  <% if not @note.new_record? %>
    <% if @note.completed_notes.present? %>
      <div class="form-inputs">
        <%= f.label :completed_notes %>
        <%= f.text_area :completed_notes, size: "50x10", placeholder: 'Enter comment here...' %>
      </div>
    <% end %>
  <% end %>

  <div class="form-actions">
    <%= link_to 'Back', branch_notes_path(@branch) , class:'btn btn-mini btn-default'%>
    <%= f.button :submit, class:'btn btn-mini btn-primary' %>
  </div>
<% end %>

app/views/notes/_notes.html.erb
<table class="table table-striped list-data-table">
  <thead>
    <tr>
      <th>Branch</th>
      <th>Code (C/B)</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <% branch = Branch.find_by_id(note.first) %>
        <td><%= branch.branch_name %></td>
        <td><%= "#{branch.company.company_code}/#{branch.branch_code}" %></td>
        <td><%= link_to note.last.count, branch_notes_path(branch), class: 'btn btn-mini btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notes/edit.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Edit Note</a></li>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid-body no-border">
      <%= render 'form', note: @note, branch: @branch, url: branch_note_path(@branch, @note), type: 'put' %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Notes</a></li>
  <% if @branch.present? %>
    <%= link_to 'Add note', new_branch_note_path(@branch), class:'btn btn-mini btn-primary pull-right' %>
  <% end %>
</ul>
<br/>
<div class="row">
  <div class="col-md-12">
    <div class="grid-body no-border">
        <br/>
        <% if @notes.present? %>
          <% if @branch.present? %>
            <% @notes.each do |note| %>
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <%= note.created_at.to_date.strftime('%d/%m/%Y') %>
                  <span class="pull-right">
                    <%= note.completed_notes.present? ? 'Completed' : '' %>
                    <%= link_to 'Edit', edit_branch_note_path(@branch, note), class: 'btn btn-mini btn-primary' %></td>
                    <%#= link_to 'Destroy', branch_note_path(@branch, note), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
                  </span>
                </div>
                <div class="panel-body">
                  <p><%= note.comment %></p>
                  <% if note.completed_notes.blank? %>
                    <br/>
                    <%= form_for(note, :url=> branch_note_path(@branch, note), :html=> {:multipart=>true,:class => 'form-inline'}) do |f| %>
                      <div class="form-group">
                        <label for="exampleInputName2">Completed Comment</label>
                        <%= f.text_area :completed_notes, size: "100x1", placeholder: 'Enter comment here...', class:"form-control" %>
                      </div>
                      <button type="submit" class="btn btn-mini btn-primary" style="margin-top:4%;">Submit</button>
                    <% end %>
                  <% else %>
                      <br/>
                      <b>Completed Notes:</b><p><%= note.completed_notes %></p>
                  <% end %>
                </div>
              </div>
          <% end %>
          <% else %>
            <%= render 'notes' %>
          <% end %>
        <% else %>
          No notes found.
        <% end %>
      </div>
  </div>
</div>

app/views/notes/new.html.erb
<ul class="breadcrumb">
  <li><p>YOU ARE HERE</p></li>
  <li><a href="#" class="active">Add Note</a></li>
</ul>
<div class="row">
  <div class="col-md-12">
    <div class="grid-body no-border">
      <%= render 'form', note: @note, branch: @branch, url: branch_notes_path(@branch), type: 'post' %>
    </div>
  </div>
</div>