config/routes.rb
Rails.application.routes.draw do
  
  resources :product_sales
  resources :sites do
    member do
      put :site_product_sale
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :factory_collections, only:[:index, :show, :new, :create]
  
  resources :reports, only:[:index] do
    collection do
      post :generate_report
      get  :generate_report
    end
  end
  resources :history_clients
  resources :templates  do
    member {
      get :send_mail
      post :send_mail_confirm
      resources :email_histories
    }
  end

  resources :email_histories, only:[] do
    member {
      get :send_email
      post :send_mail_confirm
    }
  end
  
  resources :assignments do
    member do
      get :complete_assignment
      get :pdf_assignment
    end
    collection do
      get :factory_assignments
      post :factory_assignment_submit
    end
  end
  resources :routes  do
    member do
      get :manage_branches
      get :get_route_branches
    end
    collection do
      get :schedules
      post :add_collection
    end
  end
  resources :route_branches, only:[:show] do
    collection do
      post 'sort'
    end
  end
  resources :roles
  resources :cities do
    member do
      get :get_city_areas
    end
  end
  resources :states do
    resources :cities, only:[] do
      collection do
        get :get_state_cities
      end
    end
  end
  
  resources :products do
    collection do
      post 'sort'
    end
  end
 
 
  # get 'transactions/payment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  devise_for :users
  
  resources :dashboards
  resources :companies
  resources :storage_types
  resources :food_types
  resources :billings, only: [:index] do
    member do
      get :invoice
    end
  end
  resources :areas do
    collection do
      get :get_area_branches
    end
  end
  resources :vehicles do
    collection do
      get  'assignment'
      get 'assign_branches'
      get  'get_users'
      post 'assign_vehicle'
      post 'branches_assignment'
      delete 'unassigned_branch'
    end
  end
  resources :notes, only:[:index]
  resources :branches do
    member do
      post :update_branch_status
    end
    resources :notes
    resources :transactions, only: [:index] do
      collection do
        get 'payment'
        post 'create_payment'
      end
    end
  end
  resources :schedule_branches, only:[] do
    collection do
      get 'schedules'
    end
    
  end

  resources :collections
  resources :users, only: [:index, :new] do
    collection do
      post 'add_user'
    end
    member do
      delete 'block_unblock_user'
    end
  end
end

app/views/schedules/index.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li><p>YOU ARE HERE</p></li>
      <li><a href="#" class="active">Schedules</a></li>
      <li><%= link_to 'Assignments', new_schedule_path, class:'btn btn-mini btn-primary' %></li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table table-striped">
              <thead>
              <tr>
                <th>Scheduled at</th>
                <th>Vehicle #</th>
              </tr>
              </thead>

              <tbody>
              <% @schedules.each do |schedule| %>
                  <tr>
                    <td><%= schedule.scheduled_at %></td>
                    <td><%= schedule.scheduled_at %></td>
                    <td>
                      <%= link_to '', edit_company_path(company), class:'fa fa-edit' %>
                      <%= link_to '', company, method: :delete, class:'fa fa-trash',data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>